### ISSUE TITLE
Uncaught TypeError: Cannot read property 'repo_name' of undefined

### ISSUE THREAD

**Issue by qq897425998** [jysperm/my-github-profile#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Unknown Windows Version
**Thrown From**: [my-github-profile](https://github.com/jysperm/my-github-profile) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'repo_name' of undefined

```
At C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:155

TypeError: Cannot read property 'repo_name' of undefined
  at StatusBarView.setProfile (C:\Users\89742\.atom\packages\my-github-profile\lib\main.coffee:49:62)
  at setProfile (C:\Users\89742\.atom\packages\my-github-profile\lib\main.coffee:92:38)
  at C:\Users\89742\.atom\packages\my-github-profile\lib\main.coffee:102:11
  at _fulfilled (C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:834:54)
  at self.promiseDispatch.done (C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:863:30)
  at Promise.promise.promiseDispatch (C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:796:13)
  at C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:604:44
  at runSingle (C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:137:13)
  at flush (C:\Users\89742\.atom\packages\my-github-profile\node_modules\q\q.js:125:13)
  at process._tickCallback (node.js:357:13)

```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "my-github-profile": {
    "githubToken": "58115fe3967b2e9578d2a8cb0eb13a49354f8f0f",
    "githubUsername": "897425998@qq.com"
  }
}
```
### Installed Packages

``` coffee
# User
minimap, v4.10.0
minimap-linter, v0.1.0
my-github-profile, v0.2.0
pain-split, v1.4.0
vim-mode, vundefined

# Dev
No dev packages
```

**Comment by jysperm** [comment]
抱歉，`githubUsername` 这个选项目前只接受用户名（例如 `qq897425998`），不接受邮件地址。

Sorry, `githubUsername` option now only accept username, Won't accept email address.

**Comment by qq897425998** [comment]
原来如此   谢谢
