### ISSUE TITLE
Uncaught TypeError: Cannot read property 'repo_name' of undefined

### ISSUE THREAD

**Issue by shelbyKiraM** [jysperm/my-github-profile#4]
1. Open directory that has no repo
2. Git error!
3. Get error.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.4
**Thrown From**: [ctags-status](https://github.com/mrkschan/ctags-status) package 1.3.7

### Stack Trace

Uncaught TypeError: Cannot read property 'repo_name' of undefined

```
At /Users/user/.atom/packages/ctags-status/node_modules/q/q.js:155

TypeError: Cannot read property 'repo_name' of undefined
    at StatusBarView.setProfile (/packages/my-github-profile/lib/main.coffee:57:62)
    at setProfile (/packages/my-github-profile/lib/main.coffee:116:25)
    at /packages/my-github-profile/lib/main.coffee:126:11
    at _fulfilled (/packages/ctags-status/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/packages/ctags-status/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/packages/ctags-status/node_modules/q/q.js:796:13)
    at /packages/ctags-status/node_modules/q/q.js:604:44
    at runSingle (/packages/ctags-status/node_modules/q/q.js:137:13)
    at flush (/packages/ctags-status/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -7:05.7.0 core:select-right (input.hidden-input)
     -7:03.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-ctags 5.1.2 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atomic-chrome 0.3.3 
auto-indent 0.5.0 
autocomplete-ctags 0.4.1 
base16-tomorrow-night-eighties-syntax 0.12.0 
browser-refresh 0.9.0 
busy-signal 1.4.3 
case-conversion 0.2.0 
color-picker 2.2.5 
ctags-status 1.3.7 
debug 0.0.1 
dict 0.3.1 
editorconfig 2.2.2 
emmet 2.4.3 
environment 1.3.1 
file-type-icons 1.3.4 
file-types 0.5.5 
fold-functions 0.5.0 
git-control 0.9.0 
git-diff-details 1.4.0 
go-config 1.2.4 
hard-wrap 1.7.1 
Hyrule-atom 1.2.1 
intentions 1.1.5 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.10 
marked 0.1.10 
material 2.2.0 
material-ui 1.0.10 
merge-conflicts 1.4.5 
minimap 4.29.7 
my-github-profile 0.2.1 
nucleus-dark-ui 0.12.3 
open-in-github-app 0.2.6 
php-debug 0.2.6 
pigments 0.40.2 
pretty-json 1.6.4 
remote-ftp 2.1.4 
sass-autocompile 0.13.5 
Sass-Syntax-Highlight 0.1.1 
spacegray-tomorrowdark-ui 2.1.0 
tag 0.5.0 
term3 0.22.1 
tomorrow-evening-syntax 1.1.0 
tomorrow-night-eighties 0.5.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
unity-ui 2.1.11 
url-encode 0.5.0 
vagrant 0.1.0 
```

It says it's in `ctags-status`, but I posted an issue there and they pointed out [this](https://github.com/mrkschan/ctags-status/issues/45#issuecomment-367532033):
>It seems that the error is actually raised by another package `my-github-profile` which also uses `q.js` according to the stacktrace
>
>```
>TypeError: Cannot read property 'repo_name' of undefined
>    at StatusBarView.setProfile (/packages/my-github-profile/lib/main.coffee:57:62)
>```

**Comment by joshuadanpeterson** [comment]
It happened to me as well.

[Enter steps to reproduce:]

1. Opened file in Atom
2. Got error message

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [my-github-profile](https://github.com/jysperm/my-github-profile) package 0.2.1


### Stack Trace

Uncaught TypeError: Cannot read property 'repo_name' of undefined

```
At /Users/joshpeterson/.atom/packages/my-github-profile/node_modules/q/q.js:155

TypeError: Cannot read property 'repo_name' of undefined
    at StatusBarView.setProfile (/packages/my-github-profile/lib/main.coffee:57:62)
    at setProfile (/packages/my-github-profile/lib/main.coffee:116:25)
    at /packages/my-github-profile/lib/main.coffee:126:11
    at _fulfilled (/packages/my-github-profile/node_modules/q/q.js:854:54)
    at /packages/my-github-profile/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/packages/my-github-profile/node_modules/q/q.js:816:13)
    at /packages/my-github-profile/node_modules/q/q.js:624:44
    at runSingle (/packages/my-github-profile/node_modules/q/q.js:137:13)
    at flush (/packages/my-github-profile/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Commands

```
```

### Non-Core Packages

```
ABC-notation 1.0.1 
ascii-art 1.2.0 
ascii-hex 0.2.0 
ascii-tree 1.1.0 
ask-stack 2.2.0 
atom-abc-editor 1.1.0 
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-django 0.3.2 
atom-flask 0.2.3 
atom-ghost 0.1.0 
atom-github-issues 0.4.3 
atom-hugo 0.1.2 
atom-keyboard-macros 0.12.1 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-medium 2.0.1 
atom-notes 1.20.2 
atom-python-virtualenv 1.0.4 
atom-shortcuts 0.0.2 
atom-terminal 0.8.0 
atom-ternjs 0.20.0 
atom-transcribe 0.5.1 
atom-visual-studio-code-ui 2.1.0 
atom-vlc 0.2.2 
audio 1.5.7 
audio-recorder 0.2.3 
autocomplete 0.47.0 
autocomplete-ascii-emoji 1.0.0 
autocomplete-bibtex 1.2.7 
autocomplete-emojis 2.5.0 
autocomplete-en-en 0.2.0 
autocomplete-google-suggest 1.1.0 
autocomplete-javascript 0.0.2 
autocomplete-python 1.16.0 
autocomplete-sql 0.5.0 
autocomplete-xml 0.11.0 
autocorrect-en 0.0.3 
bootstrap-3-snippets-for-atom 2.19.0 
busy-signal 2.0.1 
code-dictation 0.0.13 
css-color-name 0.4.0 
date 2.6.0 
delete-lines 0.5.0 
diagrams 0.30.0 
dictionary 0.5.0 
django-atom 0.2.4 
django-templates 0.5.0 
django-test-runner 0.5.0 
django-wrap-i18n 0.6.0 
document-outline 2.1.2 
es6-javascript 1.0.0 
file-icons 2.1.38 
flask-snippets 0.3.3 
fonts 3.10.0 
fountain 0.8.3 
foxdot 1.0.0 
gfm-pdf 0.3.5 
ginger 0.1.1 
gist 1.1.0 
gist-it 0.9.2 
github-search 0.1.0 
glist 2.2.0 
googlesearch 1.5.0 
graphviz-preview-plus 1.5.10 
gtk-dark-theme 0.1.4 
hugofy 2.0.0 
Hydrogen 2.13.1 
imdone-atom 2.4.33 
imdone-atom-github 0.1.11 
intentions 1.1.5 
javascript-regex 2.0.0 
jekyll 2.1.0 
jekyll-snippets 0.3.2 
jekyll-syntax-highlighting 0.1.0 
keyboard-heatmap 0.3.1 
keyboard-scroll 0.7.0 
keyboard-sounds 0.2.0 
kite 0.176.0 
language-alda 0.5.0 
language-applescript 0.3.0 
language-atom-notes 0.4.1 
language-autotools 2.0.1 
language-chmusick 1.2.0 
language-chordpro 0.2.5 
language-csound 0.3.5 
language-django 0.1.1 
language-dot 1.7.0 
language-hugo 0.5.1 
language-javascript-jxa 0.2.9 
language-markdown 0.37.0 
language-mediawiki 2.2.0 
language-pfm 0.82.0 
language-plantuml 0.2.0 
language-supercollider 0.2.1 
language-svg 0.9.2 
language-todotxt 1.1.5 
language-vba 0.2.5 
language-vbscript 0.9.0 
languagetool 0.1.1 
laravel-forms-bootstrap-snippets 1.2.0 
linter 2.3.1 
linter-flake8 2.4.0 
linter-languagetool 0.9.0 
linter-markdown 5.2.11 
linter-proselint 3.3.0 
linter-ui-default 1.8.1 
markdown-fold 0.3.0 
markdown-mindmap 0.6.2 
markdown-pdf 2.2.0 
markdown-preview-plus 3.11.5 
markdown-toc 0.4.2 
markdown-writer 2.11.9 
minimap 4.29.9 
mongo 0.3.0 
multi-cursor 3.0.0 
musa-dsl-atom-repl 0.1.4 
my-ascii-art 0.1.0 
my-github-profile 0.2.1 
notes-from-pdf 0.4.2 
open-html-in-browser 0.2.1 
pandoc 0.2.2 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
plantuml-preview 0.12.10 
platformio-ide-terminal 2.10.0 
predawn-syntax 1.0.4 
pretty-json 2.1.2 
preview-inline 1.5.1 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
python-autopep8 0.1.3 
Quick-JavaScript 2.2.0 
remote-ftp 2.2.4 
rhyming-dictionary 0.3.2 
rst-preview-pandoc 0.1.12 
script 3.25.0 
scroll-through-time 0.3.1 
set-syntax 0.4.0 
shortcuts-teacher 0.0.4 
slack-chat 3.4.2 
supercollider-snippets 0.1.0 
svg-preview 0.14.0 
sync-sync 2.0.2 
tablr 1.8.3 
teacode-atom-helper 1.2.3 
teletype 0.13.4 
thesaurus 0.3.0 
tidy-markdown 3.0.1 
todo 0.6.0 
tool-bar 1.2.0 
tool-bar-markdown-writer 0.5.0 
unleash-django 1.3.2 
wordcount 3.1.0 
youtubify 0.2.0 
zentabs 0.8.9 
zotero-citations 5.2.0 
```
